// Banque d'exercices personnalisée — Mon Bac 2027
// Exercices créés spécifiquement pour le parcours de la candidate.
// Ils ne remplacent pas les sujets officiels ni les exercices CNED.
window.BAC_EXERCISES = [
  {
    "id": "m2-01",
    "subject": "Maths Première",
    "chapter": "Second degré",
    "level": 1,
    "type": "Automatismes",
    "minutes": 12,
    "priority": 5,
    "prompt": "Pour f(x)=2x²−5x−3 : calcule le discriminant, les racines éventuelles et factorise f(x).",
    "solution": "Δ=25+24=49. Racines : x=(5±7)/4, donc x=3 et x=−1/2. Ainsi f(x)=2(x−3)(x+1/2)=(2x+1)(x−3)."
  },
  {
    "id": "m2-02",
    "subject": "Maths Première",
    "chapter": "Second degré",
    "level": 2,
    "type": "Application",
    "minutes": 18,
    "priority": 5,
    "prompt": "Résous l’inéquation −x²+5x−6 ≥ 0 et donne l’ensemble solution sous forme d’intervalle.",
    "solution": "−x²+5x−6=−(x−2)(x−3). La parabole est tournée vers le bas, donc l’expression est positive ou nulle entre les racines : [2;3]."
  },
  {
    "id": "m2-03",
    "subject": "Maths Première",
    "chapter": "Second degré",
    "level": 3,
    "type": "Type bac",
    "minutes": 25,
    "priority": 5,
    "prompt": "Une aire rectangulaire a un périmètre de 40 m. Si x est sa largeur, exprime son aire A(x), puis détermine la largeur qui maximise l’aire.",
    "solution": "Longueur=20−x. A(x)=x(20−x)=−x²+20x. Forme canonique : A(x)=−(x−10)²+100. Maximum 100 m² pour x=10 m."
  },
  {
    "id": "ms-01",
    "subject": "Maths Première",
    "chapter": "Suites",
    "level": 1,
    "type": "Automatismes",
    "minutes": 10,
    "priority": 5,
    "prompt": "Une suite arithmétique vérifie u₀=7 et raison r=−3. Calcule u₅ puis donne uₙ.",
    "solution": "u₅=7+5(−3)=−8. uₙ=7−3n."
  },
  {
    "id": "ms-02",
    "subject": "Maths Première",
    "chapter": "Suites",
    "level": 2,
    "type": "Application",
    "minutes": 18,
    "priority": 5,
    "prompt": "Une population augmente de 4 % par an à partir de 12 500 habitants. Modélise par une suite et estime la population après 6 ans.",
    "solution": "Suite géométrique uₙ=12500×1,04ⁿ. u₆≈15 817 habitants."
  },
  {
    "id": "md-01",
    "subject": "Maths Première",
    "chapter": "Dérivation et variations",
    "level": 1,
    "type": "Automatismes",
    "minutes": 12,
    "priority": 5,
    "prompt": "Dérive f(x)=3x³−5x²+4x−7.",
    "solution": "f'(x)=9x²−10x+4."
  },
  {
    "id": "md-02",
    "subject": "Maths Première",
    "chapter": "Dérivation et variations",
    "level": 2,
    "type": "Application",
    "minutes": 20,
    "priority": 5,
    "prompt": "Étudie les variations de f(x)=x³−3x sur [−2;2].",
    "solution": "f'(x)=3x²−3=3(x−1)(x+1). f est croissante sur [−2;−1], décroissante sur [−1;1], croissante sur [1;2]."
  },
  {
    "id": "me-01",
    "subject": "Maths Première",
    "chapter": "Fonction exponentielle",
    "level": 2,
    "type": "Application",
    "minutes": 18,
    "priority": 5,
    "prompt": "Résous 3e^(0,2t)=12 puis donne une valeur approchée de t.",
    "solution": "e^(0,2t)=4, donc 0,2t=ln4 et t=5ln4≈6,93."
  },
  {
    "id": "mt-01",
    "subject": "Maths Première",
    "chapter": "Trigonométrie",
    "level": 1,
    "type": "Automatismes",
    "minutes": 12,
    "priority": 4,
    "prompt": "Donne cos(π/3), sin(π/6), puis les solutions de cos x=1/2 sur [0;2π].",
    "solution": "cos(π/3)=1/2, sin(π/6)=1/2. cos x=1/2 pour x=π/3 ou 5π/3 sur [0;2π]."
  },
  {
    "id": "mg-01",
    "subject": "Maths Première",
    "chapter": "Produit scalaire",
    "level": 2,
    "type": "Application",
    "minutes": 20,
    "priority": 4,
    "prompt": "Dans un repère orthonormé, A(1;2), B(4;3), C(2;−1). Calcule AB·AC et déduis si l’angle BAC est aigu, droit ou obtus.",
    "solution": "AB=(3;1), AC=(1;−3). Produit scalaire=3−3=0. L’angle BAC est droit."
  },
  {
    "id": "mp-01",
    "subject": "Maths Première",
    "chapter": "Probabilités conditionnelles",
    "level": 2,
    "type": "Application",
    "minutes": 18,
    "priority": 5,
    "prompt": "On sait P(A)=0,6, P(B|A)=0,3 et P(B|Ā)=0,1. Calcule P(B).",
    "solution": "P(B)=P(A)P(B|A)+P(Ā)P(B|Ā)=0,6×0,3+0,4×0,1=0,22."
  },
  {
    "id": "mv-01",
    "subject": "Maths Première",
    "chapter": "Variables aléatoires",
    "level": 2,
    "type": "Application",
    "minutes": 18,
    "priority": 4,
    "prompt": "Une variable X prend les valeurs 0, 2 et 5 avec probabilités 0,2 ; 0,5 ; 0,3. Calcule E(X).",
    "solution": "E(X)=0×0,2+2×0,5+5×0,3=2,5."
  },
  {
    "id": "fr-01",
    "subject": "Français Première",
    "chapter": "Commentaire",
    "level": 1,
    "type": "Méthode",
    "minutes": 15,
    "priority": 5,
    "prompt": "À partir d’un extrait de ton cours, écris une problématique de commentaire qui ne reformule pas simplement le thème du texte.",
    "solution": "Une bonne problématique met en tension un procédé et un effet. Modèle : « Comment l’auteur transforme-t-il [situation] en [effet / portée] grâce à [mécanisme d’écriture] ? »"
  },
  {
    "id": "fr-02",
    "subject": "Français Première",
    "chapter": "Commentaire",
    "level": 2,
    "type": "Méthode",
    "minutes": 25,
    "priority": 5,
    "prompt": "Prends un texte déjà étudié et construis un plan en 2 ou 3 axes. Pour chaque axe, note 2 procédés précis et l’effet produit.",
    "solution": "Vérifie : axes progressifs, procédés nommés précisément, citation courte ou repérage, interprétation. Aucun axe ne doit être un simple résumé."
  },
  {
    "id": "fr-03",
    "subject": "Français Première",
    "chapter": "Dissertation",
    "level": 2,
    "type": "Méthode",
    "minutes": 25,
    "priority": 5,
    "prompt": "Sur une œuvre au programme, transforme un sujet affirmatif en question problématisée puis construis un plan dialectique ou thématique.",
    "solution": "La problématique doit faire apparaître une difficulté réelle. Le plan doit répondre progressivement à cette difficulté et mobiliser l’œuvre ainsi que le parcours."
  },
  {
    "id": "fr-04",
    "subject": "Français Première",
    "chapter": "Oral EAF",
    "level": 2,
    "type": "Oral",
    "minutes": 20,
    "priority": 5,
    "prompt": "Choisis un texte du récapitulatif. En 8 minutes, prépare : introduction, mouvement du texte, problématique et 3 observations linéaires.",
    "solution": "Contrôle : contextualisation brève, découpage justifié, analyse liée au texte, termes littéraires précis, conclusion répondant à la problématique."
  },
  {
    "id": "fr-05",
    "subject": "Français Première",
    "chapter": "Grammaire",
    "level": 1,
    "type": "Automatismes",
    "minutes": 12,
    "priority": 4,
    "prompt": "Dans trois phrases de ton corpus, repère une proposition subordonnée, donne sa nature et sa fonction.",
    "solution": "Méthode : identifier le mot subordonnant, isoler la proposition, déterminer sa nature (relative, conjonctive, interrogative indirecte…) puis sa fonction dans la phrase."
  },
  {
    "id": "fr-06",
    "subject": "Français Première",
    "chapter": "Analyse littéraire",
    "level": 1,
    "type": "Automatismes",
    "minutes": 15,
    "priority": 4,
    "prompt": "Trouve dans un texte 5 procédés différents et, pour chacun, formule l’effet produit sans employer « ça montre que ».",
    "solution": "Exemples de formulations : « souligne », « accentue », « crée », « oppose », « donne à voir », « met en tension », « suggère », « produit un effet de… »."
  },
  {
    "id": "fr-07",
    "subject": "Français Première",
    "chapter": "Entretien oral",
    "level": 2,
    "type": "Oral",
    "minutes": 15,
    "priority": 4,
    "prompt": "Prépare une présentation de 2 minutes d’une œuvre choisie pour l’entretien : choix personnel, thème central, passage marquant, lien avec le parcours.",
    "solution": "La présentation doit être personnelle mais argumentée. Évite le résumé exhaustif ; privilégie 2 ou 3 raisons précises et illustrées."
  },
  {
    "id": "ses-01",
    "subject": "SES Terminale",
    "chapter": "Croissance économique",
    "level": 2,
    "type": "Question de cours",
    "minutes": 18,
    "priority": 5,
    "prompt": "Explique en 12 à 15 lignes comment le progrès technique peut soutenir la croissance tout en produisant des effets de destruction créatrice.",
    "solution": "Attendus : gains de productivité, innovation de produit/procédé, croissance endogène, rentes temporaires, disparition d’activités/emplois anciens et création de nouveaux secteurs."
  },
  {
    "id": "ses-02",
    "subject": "SES Terminale",
    "chapter": "Commerce international",
    "level": 2,
    "type": "Plan",
    "minutes": 20,
    "priority": 5,
    "prompt": "Construis un plan détaillé : « Quels sont les déterminants de la spécialisation internationale ? »",
    "solution": "Attendus possibles : avantages comparatifs/dotations ; différenciation et commerce intra-branche ; fragmentation des chaînes de valeur et compétitivité."
  },
  {
    "id": "ses-03",
    "subject": "SES Terminale",
    "chapter": "Chômage",
    "level": 2,
    "type": "Application",
    "minutes": 20,
    "priority": 5,
    "prompt": "Distingue chômage conjoncturel et structurel, puis associe à chacun deux mécanismes explicatifs et une politique possible.",
    "solution": "Conjoncturel : insuffisance de demande, ralentissement ; politiques de soutien de la demande. Structurel : inadéquations, rigidités, appariement ; formation, mobilité, politiques du marché du travail."
  },
  {
    "id": "ses-04",
    "subject": "SES Terminale",
    "chapter": "Politiques économiques européennes",
    "level": 3,
    "type": "Type bac",
    "minutes": 30,
    "priority": 5,
    "prompt": "Explique pourquoi la coordination des politiques économiques est nécessaire dans une union monétaire.",
    "solution": "Attendus : politique monétaire commune, interdépendances, externalités, divergences conjoncturelles, contraintes budgétaires, coordination pour stabiliser et éviter les effets de débordement."
  },
  {
    "id": "ses-05",
    "subject": "SES Terminale",
    "chapter": "Structure de la société française",
    "level": 2,
    "type": "Question de cours",
    "minutes": 18,
    "priority": 4,
    "prompt": "Présente quatre facteurs qui structurent et hiérarchisent l’espace social en France.",
    "solution": "Exemples : PCS, revenu/patrimoine, diplôme, genre, âge/génération, lieu de résidence, composition du ménage. Il faut expliquer le mécanisme, pas seulement lister."
  },
  {
    "id": "ses-06",
    "subject": "SES Terminale",
    "chapter": "Mobilité sociale",
    "level": 2,
    "type": "Données",
    "minutes": 22,
    "priority": 4,
    "prompt": "Explique la différence entre mobilité observée et fluidité sociale, puis indique pourquoi une hausse de la mobilité observée ne signifie pas nécessairement plus d’égalité des chances.",
    "solution": "Mobilité observée = changements de position. Fluidité = force du lien entre origine et position sociale. La structure des emplois peut accroître les déplacements sans réduire l’inégalité relative des chances."
  },
  {
    "id": "ses-07",
    "subject": "SES Terminale",
    "chapter": "Travail et emploi",
    "level": 2,
    "type": "Plan",
    "minutes": 20,
    "priority": 4,
    "prompt": "Construis un plan : « Comment les évolutions de l’organisation du travail transforment-elles les conditions de travail ? »",
    "solution": "Mobiliser taylorisme/fordisme, post-taylorisme, autonomie, contrôle, numérique, polarisation des effets, qualité de l’emploi et risques psychosociaux."
  },
  {
    "id": "ses-08",
    "subject": "SES Terminale",
    "chapter": "Engagement politique",
    "level": 2,
    "type": "Question de cours",
    "minutes": 18,
    "priority": 4,
    "prompt": "Montre que les formes de l’engagement politique sont diversifiées et que leurs déterminants sont multiples.",
    "solution": "Participation conventionnelle/non conventionnelle, vote, militantisme, association, consommation engagée ; variables sociodémographiques, socialisation, compétences politiques, rétributions, contexte."
  },
  {
    "id": "ses-09",
    "subject": "SES Terminale",
    "chapter": "Action publique pour l’environnement",
    "level": 3,
    "type": "Type bac",
    "minutes": 30,
    "priority": 5,
    "prompt": "Compare réglementation, taxation et marché de quotas pour réduire les externalités négatives environnementales.",
    "solution": "Comparer principe, incitations, information nécessaire, coût, efficacité, acceptabilité, effets distributifs. Aucun instrument n’est optimal en toutes circonstances."
  },
  {
    "id": "hggsp2-01",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 2 — Faire la guerre, faire la paix",
    "level": 2,
    "type": "Question problématisée",
    "minutes": 25,
    "priority": 5,
    "prompt": "Explique en quoi la pensée de Clausewitz permet de comprendre certaines guerres mais connaît aussi des limites pour les conflits contemporains.",
    "solution": "Attendus : guerre comme acte politique, duel, montée aux extrêmes, guerre réelle/absolue ; limites face aux acteurs non étatiques, asymétries, terrorisme, hybridation et conflictualités diffuses."
  },
  {
    "id": "hggsp2-02",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 2 — Faire la guerre, faire la paix",
    "level": 3,
    "type": "Dissertation",
    "minutes": 35,
    "priority": 5,
    "prompt": "Propose problématique et plan détaillé : « Faire la paix depuis 1648 : entre équilibre des puissances et sécurité collective ».",
    "solution": "Plan possible : Westphalie et équilibre ; XIXe-XXe tentatives multilatérales ; ONU et sécurité collective, avancées et limites. Illustrer précisément."
  },
  {
    "id": "hggsp4-01",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 4 — Patrimoine",
    "level": 2,
    "type": "Étude critique",
    "minutes": 25,
    "priority": 5,
    "prompt": "À partir d’un exemple patrimonial vu en cours, distingue les enjeux de conservation, de valorisation, d’usage politique et de développement économique.",
    "solution": "Une bonne réponse distingue les acteurs, les échelles, les conflits d’usage et les effets de la patrimonialisation."
  },
  {
    "id": "hggsp4-02",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 4 — Patrimoine",
    "level": 3,
    "type": "Dissertation",
    "minutes": 35,
    "priority": 5,
    "prompt": "Construis un plan : « Le patrimoine est-il seulement un héritage à protéger ? »",
    "solution": "Montrer qu’il est construit/sélectionné, qu’il porte identités et mémoires, qu’il est ressource économique et géopolitique, et peut devenir objet de conflits."
  },
  {
    "id": "hggsp5-01",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 5 — Environnement",
    "level": 2,
    "type": "Question problématisée",
    "minutes": 25,
    "priority": 5,
    "prompt": "Montre que les relations des sociétés à l’environnement combinent exploitation, protection et transformations des représentations.",
    "solution": "Mobiliser temporalités longues, industrialisation, ressources, conservation, changement climatique, acteurs et échelles."
  },
  {
    "id": "hggsp5-02",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 5 — Environnement",
    "level": 3,
    "type": "Dissertation",
    "minutes": 35,
    "priority": 5,
    "prompt": "Construis problématique et plan : « Le changement climatique, enjeu de coopération internationale et de rivalités ».",
    "solution": "Articuler diagnostic global, négociations et gouvernance, intérêts divergents, responsabilités différenciées, financements, puissance et tensions géopolitiques."
  },
  {
    "id": "hggsp6-01",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 6 — L’enjeu de la connaissance",
    "level": 2,
    "type": "Question problématisée",
    "minutes": 25,
    "priority": 5,
    "prompt": "Explique pourquoi la production et la diffusion de la connaissance constituent un enjeu de puissance.",
    "solution": "Éducation/recherche, innovation, brevets, données, réseaux scientifiques, attractivité, renseignement, contrôle de l’information et souveraineté technologique."
  },
  {
    "id": "hggsp6-02",
    "subject": "HGGSP Terminale",
    "chapter": "Thème 6 — L’enjeu de la connaissance",
    "level": 3,
    "type": "Étude critique",
    "minutes": 30,
    "priority": 5,
    "prompt": "Choisis un exemple du cours et montre comment circulation de la connaissance et secret peuvent coexister.",
    "solution": "Identifier acteurs, intérêt à diffuser/cooperer, intérêt à protéger, dispositifs de secret, effets sur puissance et innovation."
  },
  {
    "id": "ph-01",
    "subject": "Philosophie",
    "chapter": "Dissertation",
    "level": 2,
    "type": "Méthode",
    "minutes": 25,
    "priority": 3,
    "prompt": "Sujet : « Être libre, est-ce faire ce que l’on veut ? » Dégage les termes, la difficulté et formule une problématique.",
    "solution": "Distinguer désir/volonté, absence de contrainte/autonomie. Difficulté : suivre tous ses désirs peut conduire à une forme de dépendance. La problématique doit faire apparaître cette tension."
  },
  {
    "id": "ph-02",
    "subject": "Philosophie",
    "chapter": "Explication de texte",
    "level": 2,
    "type": "Méthode",
    "minutes": 20,
    "priority": 3,
    "prompt": "Sur un extrait philosophique du CNED, formule en une phrase la thèse, puis découpe le mouvement argumentatif en 2 ou 3 étapes.",
    "solution": "La thèse n’est pas le thème. Chaque mouvement doit correspondre à une fonction argumentative : poser, distinguer, réfuter, démontrer, conclure…"
  },
  {
    "id": "ph-03",
    "subject": "Philosophie",
    "chapter": "Notions",
    "level": 1,
    "type": "Automatismes",
    "minutes": 15,
    "priority": 3,
    "prompt": "Pour vérité, liberté et justice : donne une définition de travail, une distinction utile et un exemple problématique pour chaque notion.",
    "solution": "Objectif : disposer d’un kit conceptuel mobilisable. Les distinctions doivent être opératoires, pas récitées sans lien avec un problème."
  },
  {
    "id": "hg-01",
    "subject": "Histoire-géographie",
    "chapter": "Première — Première Guerre mondiale",
    "level": 2,
    "type": "Synthèse",
    "minutes": 25,
    "priority": 4,
    "prompt": "En 15 lignes, explique pourquoi la Première Guerre mondiale est une guerre totale et une expérience de violence de masse.",
    "solution": "Mobiliser fronts/arrière, mobilisation économique et sociale, propagande, civils, violences combattantes, génocide des Arméniens, bilan humain et matériel."
  },
  {
    "id": "hg-02",
    "subject": "Histoire-géographie",
    "chapter": "Première — IIIe République",
    "level": 2,
    "type": "Synthèse",
    "minutes": 25,
    "priority": 4,
    "prompt": "Construis une fiche en 6 points : enracinement républicain, libertés, laïcité, crises, société, empire colonial.",
    "solution": "La fiche doit articuler institutions, pratiques politiques, culture républicaine, conflits et limites, sans juxtaposer des dates."
  },
  {
    "id": "hg-03",
    "subject": "Histoire-géographie",
    "chapter": "Première — Métropolisation",
    "level": 2,
    "type": "Croquis / notions",
    "minutes": 25,
    "priority": 4,
    "prompt": "Définis métropolisation puis explique trois effets spatiaux observables à l’échelle mondiale et dans une métropole.",
    "solution": "Concentration des fonctions supérieures et populations ; hiérarchisation des villes, fragmentation/ségrégation, étalement, recompositions des mobilités et centralités."
  },
  {
    "id": "hg-04",
    "subject": "Histoire-géographie",
    "chapter": "Première — Espaces productifs",
    "level": 2,
    "type": "Étude de cas",
    "minutes": 25,
    "priority": 4,
    "prompt": "À partir d’un espace productif étudié, explique comment il s’insère dans la mondialisation et se recompose.",
    "solution": "Localisation, acteurs, réseaux/flux, avantages, innovation, concurrence, transition et recomposition territoriale."
  },
  {
    "id": "hg-05",
    "subject": "Histoire-géographie",
    "chapter": "Terminale — 1929 à 1945",
    "level": 2,
    "type": "Pont Première-Terminale",
    "minutes": 25,
    "priority": 4,
    "prompt": "Fais une frise 1918–1945 avec 10 repères et, pour chacun, indique en quelques mots son lien avec la crise des démocraties et la guerre.",
    "solution": "Objectif : construire les enchaînements plutôt qu’une liste de dates isolées : sortie de guerre, crise, totalitarismes, tensions, guerre mondiale."
  },
  {
    "id": "sci-01",
    "subject": "Enseignement scientifique",
    "chapter": "Première — Énergie / Soleil",
    "level": 2,
    "type": "Application",
    "minutes": 20,
    "priority": 3,
    "prompt": "À partir d’un document donnant puissance reçue et surface, calcule une énergie reçue sur une durée puis interprète l’ordre de grandeur.",
    "solution": "Identifier les unités, utiliser E=P×Δt, convertir correctement la durée, puis commenter la cohérence de l’ordre de grandeur."
  },
  {
    "id": "sci-02",
    "subject": "Enseignement scientifique",
    "chapter": "Première — Son et musique",
    "level": 2,
    "type": "Application",
    "minutes": 20,
    "priority": 3,
    "prompt": "Explique la différence entre fréquence, période, hauteur et intensité sonore, puis relie-les à un signal sinusoïdal.",
    "solution": "T=1/f ; fréquence ↔ hauteur ; amplitude/intensité ↔ niveau sonore. Ne pas confondre fréquence et amplitude."
  },
  {
    "id": "sci-03",
    "subject": "Enseignement scientifique",
    "chapter": "Méthode scientifique",
    "level": 2,
    "type": "Documents",
    "minutes": 20,
    "priority": 3,
    "prompt": "Prends un graphique scientifique du CNED : formule une lecture descriptive, puis une interprétation, puis une limite.",
    "solution": "Séparer ce que montre le document de l’explication. Citer axes/unités/tendance ; interpréter avec le cours ; signaler incertitude, corrélation/causalité ou limites de l’échantillon."
  },
  {
    "id": "lv-01",
    "subject": "Langues",
    "chapter": "Expression orale",
    "level": 2,
    "type": "Oral",
    "minutes": 15,
    "priority": 2,
    "prompt": "Choisis un axe étudié. Parle 2 minutes sans notes : définition du thème, un exemple précis, ton analyse, une ouverture.",
    "solution": "Objectif : discours structuré et intelligible. Utilise 5 connecteurs, 3 mots de vocabulaire thématique et au moins une phrase complexe."
  },
  {
    "id": "lv-02",
    "subject": "Langues",
    "chapter": "Expression écrite",
    "level": 2,
    "type": "Écrit",
    "minutes": 20,
    "priority": 2,
    "prompt": "Rédige 150 à 180 mots sur un sujet lié à un axe du programme en utilisant introduction, deux paragraphes argumentés et conclusion.",
    "solution": "Contrôle : réponse au sujet, organisation, variété lexicale, temps cohérents, connecteurs, relecture ciblée sur accords et syntaxe."
  },
  {
    "id": "emc-01",
    "subject": "EMC",
    "chapter": "Argumentation civique",
    "level": 2,
    "type": "Documents",
    "minutes": 20,
    "priority": 2,
    "prompt": "À partir d’un document d’actualité fourni par le CNED, identifie le principe civique en jeu, les acteurs, le conflit de droits ou d’intérêts et propose une réponse argumentée.",
    "solution": "Réponse attendue : principe défini, document exploité précisément, pluralité des positions, argumentation fondée sur règles/institutions et non sur une simple opinion."
  }
];
